version: '3.8'

networks:
  forensic_net:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: forensic_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forensic_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forensic_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: forensic_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - forensic_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: forensic_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forensic_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SECRET_KEY=clave_super_secreta_cambiar_en_produccion
    networks:
      - forensic_net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    build: .
    container_name: forensic_worker
    command: python worker/worker.py
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forensic_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - forensic_net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: always

  vuln-scanner:
    build:
      context: .
      dockerfile: scanner/Dockerfile
    container_name: forensic_vuln_scanner
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/forensic_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - forensic_net
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    cap_add:
      - NET_RAW
      - NET_ADMIN
    restart: always

volumes:
  postgres_data:


   