apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: asm
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: api-gateway
          image: TU_USUARIO/asm-api-gateway:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: asm-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: asm
spec:
  selector:
    app: api-gateway
  ports:
    - port: 8000
      targetPort: 8000
